services:
  db:
    image: postgres:15.3
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=webcrawlerdb
    ports:
      - "54321:5432"
    volumes:
      - db_volume:/var/lib/porsgresql/data
volumes:
  db_volume: